-- Custom personas generated by AI on demand
CREATE TABLE public.custom_personas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL DEFAULT 'custom',
  short_bio text NOT NULL,
  voice_prompt text NOT NULL,
  signature_phrases jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.custom_personas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read custom personas"
  ON public.custom_personas FOR SELECT
  USING (true);

CREATE POLICY "Anyone can create custom personas"
  ON public.custom_personas FOR INSERT
  WITH CHECK (true);

-- Rewritten landings, addressable by public_id for share links
CREATE TABLE public.rewrites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id text NOT NULL UNIQUE,
  source_url text NOT NULL,
  persona_id text NOT NULL,
  persona_name text NOT NULL,
  html_original text NOT NULL,
  html_rewritten text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.rewrites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read rewrites by public_id"
  ON public.rewrites FOR SELECT
  USING (true);

CREATE POLICY "Anyone can create rewrites"
  ON public.rewrites FOR INSERT
  WITH CHECK (true);

CREATE INDEX rewrites_public_id_idx ON public.rewrites(public_id);
CREATE INDEX custom_personas_slug_idx ON public.custom_personas(slug);